name: build

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'config/**'
      - 'tests/**'
      - 'phpunit.xml.dist'
      - 'phpunit-with-intl.xml'
      - 'composer.json'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      extensions: :intl
      coverage: xdebug
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
  phpunit-with-intl:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      phpunitConfig: phpunit-with-intl.xml
      extensions: intl
      coverage: xdebug
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
